version: '3'

services:
  nextcloud:
    image: nextcloud
    ports:
      - "80:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=secret
      # use S3 bucket as external storage
      - OBJECTSTORE_CLASS=\\OC\\Files\\ObjectStore\\S3
      - OBJECTSTORE_BUCKET=${bucket_name}
      - OBJECTSTORE_REGION=${region}
      - OBJECTSTORE_USE_SSL=true
      - DATADIRECTORY=s3://${bucket_name}/nextcloud_data
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  nextcloud_data:
  db_data:
