name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev --deploy

    - name: Run pre-commit hooks
      run: pipenv run pre-commit run --all-files

    - name: Run Trivy scanner for vulnerabilities, miconfigured IaC, secrets and license
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scanners: 'vuln,config,secret,license'
        trivyignores: '.trivyignore.yaml'
        hide-progress: false
        exit-code: '1'
        ignore-unfixed: false
        severity: 'CRITICAL,HIGH,MEDIUM'
